<?php
/**
 * Model User
 *
 * @link https://docs.phalconphp.com/en/latest/reference/models.html
 * @author Edvard
 * @time 2015.12.14 12:13
 */

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\PresenceOf;
use Phalcon\Mvc\Model\Message;

class User extends BaseModel
{

    /**
     *
     * @var integer
     */
    public $id;

    /**
     *
     * @var integer
     */
    public $parent_id;

    /**
     *
     * @var string
     */
    public $username;

    /**
     *
     * @var string
     */
    public $password;

    /**
     *
     * @var string
     */
    public $name;

    /**
     *
     * @var string
     */
    public $organization;

    /**
     *
     * @var string
     */
    public $title;

    /**
     *
     * @var string
     */
    public $mobile_country_code;

    /**
     *
     * @var string
     */
    public $mobile_number;

    /**
     *
     * @var string
     */
    public $email;

    /**
     *
     * @var integer
     */
    public $sms_privilege;

    /**
     *
     * @var double
     */
    public $deposite_balance;

    /**
     *
     * @var integer
     */
    public $creator;

    /**
     *
     * @var string
     */
    public $created_time;

    /**
     *
     * @var integer
     */
    public $modifier;

    /**
     *
     * @var string
     */
    public $modified_time;

    /**
     *
     * @var integer
     */
    public $isdeleted;

    /**
     *
     * @var integer
     */
    public $deletor;

    /**
     *
     * @var string
     */
    public $deleted_time;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 映射到那张表
     */
    public function getSource()
    {
        return 'user';
    }

    /**
     * @return bool
     */
    public function validation()
    {
        $this->validate(
            new Uniqueness(
                array(
                    "field" => "username",
                    "message" => "The name must be unique"
                )
            )
        );

        $this->validate(new PresenceOf(
            array(
                "field" => 'username',
                "message" => 'The username is required'
            )
        ));

        $this->validate(new PresenceOf(
            array(
                "field" => 'password',
                "message" => 'The password is required'
            )
        ));

        // 验证是否失败
        if ($this->validationHasFailed() == true) {
            return false;
        }

        return true;
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return User[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return User
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * @param $username
     * @param $password
     * @return bool|User
     */
    public function login($username, $password)
    {
        if (empty($username)) {
            $this->appendMessage(new Message('The username is required', 'username', 'PresenceOf'));
            return false;
        }

        if (empty($password)) {
            $this->appendMessage(new Message('The password is required', 'password', 'PresenceOf'));
            return false;
        }

        // 用户名不分大小写
        $user = $this->findFirst("lower(username)='" . strtolower($username) . "'");

        if (false == $user) {
            $this->appendMessage(new Message('The username is incorrect', 'username', 'Inclusion'));
            return false;
        }

        if (!password_verify($password, $user->password)) {
            $this->appendMessage(new Message('The password is incorrect', 'password', 'Inclusion'));
            return false;
        }

        return $user;
    }

    public function createUser($user)
    {
        $this->username = $user['username'];
        if (!empty($user['password'])) {
            $this->password = password_hash($user['password'], PASSWORD_DEFAULT);
        }
        $this->name = $user['name'];
        $this->title = $user['title'];
        if (!filter_var($user['email'], FILTER_VALIDATE_EMAIL)) {
            $this->appendMessage(new Message('The email is incorrect', 'email', 'Inclusion'));
            return false;
        }
        $this->email = $user['email'];

        $res = $this->save();
        if (false == $res) {
            return $res;
        }

        return $res;
    }
}