<?php
/**
 * Model User
 *
 * @link https://docs.phalconphp.com/en/latest/reference/models.html
 * @author Edvard
 * @time 2015.12.14 12:13
 */

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\PresenceOf;
use Phalcon\Mvc\Model\Message;

class User extends BaseModel
{

    /**
     *
     * @var integer
     */
    public $id;

    /**
     *
     * @var integer
     */
    public $parent_id;

    /**
     *
     * @var string
     */
    public $username;

    /**
     *
     * @var string
     */
    public $password;

    /**
     *
     * @var string
     */
    public $name;

    /**
     *
     * @var string
     */
    public $organization;

    /**
     *
     * @var string
     */
    public $title;

    /**
     *
     * @var string
     */
    public $mobile_country_code;

    /**
     *
     * @var string
     */
    public $mobile_number;

    /**
     *
     * @var string
     */
    public $email;

    /**
     *
     * @var integer
     */
    public $sms_privilege;

    /**
     *
     * @var double
     */
    public $deposite_balance;

    /**
     *
     * @var integer
     */
    public $creator;

    /**
     *
     * @var string
     */
    public $created_time;

    /**
     *
     * @var integer
     */
    public $modifier;

    /**
     *
     * @var string
     */
    public $modified_time;

    /**
     *
     * @var integer
     */
    public $isdeleted;

    /**
     *
     * @var integer
     */
    public $deletor;

    /**
     *
     * @var string
     */
    public $deleted_time;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 映射到那张表
     */
    public function getSource()
    {
        return 'user';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return User[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return User
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * @param $username
     * @param $password
     * @return bool|User
     */
    public function login($username, $password)
    {
        // 用户名不分大小写
        $user = $this->findFirst("lower(username)='" . strtolower($username) . "'");

        if (false == $user) {
            $this->appendMessage(new Message('The username is incorrect', 'username', 'Inclusion'));
            return false;
        }

        if (!password_verify($password, $user->password)) {
            $this->appendMessage(new Message('The password is incorrect', 'password', 'Inclusion'));
            return false;
        }

        return $user;
    }
}